/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NovoRouteImport } from './routes/novo'
import { Route as TreinoIdRouteImport } from './routes/treino.$id'
import { Route as TreinoIdIndexRouteImport } from './routes/treino.$id.index'
import { Route as TreinoIdEditarRouteImport } from './routes/treino.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoRoute = NovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoIdRoute = TreinoIdRouteImport.update({
  id: '/treino/$id',
  path: '/treino/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoIdIndexRoute = TreinoIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreinoIdRoute,
} as any)
const TreinoIdEditarRoute = TreinoIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => TreinoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/novo': typeof NovoRoute
  '/treino/$id': typeof TreinoIdRouteWithChildren
  '/treino/$id/editar': typeof TreinoIdEditarRoute
  '/treino/$id/': typeof TreinoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/novo': typeof NovoRoute
  '/treino/$id/editar': typeof TreinoIdEditarRoute
  '/treino/$id': typeof TreinoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/novo': typeof NovoRoute
  '/treino/$id': typeof TreinoIdRouteWithChildren
  '/treino/$id/editar': typeof TreinoIdEditarRoute
  '/treino/$id/': typeof TreinoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/novo'
    | '/treino/$id'
    | '/treino/$id/editar'
    | '/treino/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/novo' | '/treino/$id/editar' | '/treino/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/novo'
    | '/treino/$id'
    | '/treino/$id/editar'
    | '/treino/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  NovoRoute: typeof NovoRoute
  TreinoIdRoute: typeof TreinoIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo': {
      id: '/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof NovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino/$id': {
      id: '/treino/$id'
      path: '/treino/$id'
      fullPath: '/treino/$id'
      preLoaderRoute: typeof TreinoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino/$id/': {
      id: '/treino/$id/'
      path: '/'
      fullPath: '/treino/$id/'
      preLoaderRoute: typeof TreinoIdIndexRouteImport
      parentRoute: typeof TreinoIdRoute
    }
    '/treino/$id/editar': {
      id: '/treino/$id/editar'
      path: '/editar'
      fullPath: '/treino/$id/editar'
      preLoaderRoute: typeof TreinoIdEditarRouteImport
      parentRoute: typeof TreinoIdRoute
    }
  }
}

interface TreinoIdRouteChildren {
  TreinoIdEditarRoute: typeof TreinoIdEditarRoute
  TreinoIdIndexRoute: typeof TreinoIdIndexRoute
}

const TreinoIdRouteChildren: TreinoIdRouteChildren = {
  TreinoIdEditarRoute: TreinoIdEditarRoute,
  TreinoIdIndexRoute: TreinoIdIndexRoute,
}

const TreinoIdRouteWithChildren = TreinoIdRoute._addFileChildren(
  TreinoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  NovoRoute: NovoRoute,
  TreinoIdRoute: TreinoIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
