import type { Workout } from "./types";

function w(
  partial: Omit<Workout, "createdAt" | "athletes" | "sets" | "reps" | "extras" | "core" | "cardio" | "notes" | "focusLabel"> &
    Partial<Pick<Workout, "athletes" | "sets" | "reps" | "extras" | "core" | "cardio" | "notes" | "focusLabel" | "createdAt">>,
): Workout {
  const focusLabel =
    partial.focusLabel ??
    (partial.focus === "pernas" ? "Pernas" : partial.focus === "bracos" ? "Braços" : "Outro");
  return {
    athletes: ["Geovanil", "Vânia"],
    sets: 3,
    reps: 12,
    extras: "",
    core: [],
    cardio: [],
    notes: "",
    createdAt: `${partial.date}T12:00:00.000Z`,
    focusLabel,
    ...partial,
  };
}

export const SEED_WORKOUTS: Workout[] = [
  w({
    id: "seed-2026-09-07",
    date: "2026-09-07",
    focus: "pernas",
    durationMin: 90,
    intensity: "forte",
    machines: 5,
    reps: 10,
    muscleGroups: ["anteriores", "posteriores"],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-09-06",
    date: "2026-09-06",
    focus: "pernas",
    durationMin: 79,
    intensity: "forte",
    machines: 5,
    reps: 10,
    muscleGroups: ["anteriores", "posteriores"],
    core: [
      { exercise: "Abdominal", sets: 3, reps: 20, athlete: "Geovanil" },
      { exercise: "Abdominal", sets: 3, reps: 12, athlete: "Vânia" },
    ],
  }),
  w({
    id: "seed-2026-09-02",
    date: "2026-09-02",
    focus: "bracos",
    durationMin: 90,
    intensity: "forte",
    machines: 3,
    reps: 10,
    muscleGroups: ["peito", "costas"],
    extras: "3 halteres",
    core: [{ exercise: "Abdominal", sets: 3, reps: 20 }],
  }),
  w({
    id: "seed-2026-09-01",
    date: "2026-09-01",
    focus: "pernas",
    durationMin: 80,
    intensity: "forte",
    machines: 6,
    reps: 10,
    muscleGroups: ["anteriores", "posteriores"],
    core: [{ exercise: "Abdominal", sets: 3, reps: 20 }],
  }),
  w({
    id: "seed-2026-08-31",
    date: "2026-08-31",
    focus: "bracos",
    durationMin: 80,
    intensity: "forte",
    machines: 6,
    reps: 10,
    muscleGroups: ["peito", "costas"],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12, athlete: "Geovanil" }],
    cardio: [{ kind: "Bike", minutes: 10 }],
  }),
  w({
    id: "seed-2026-08-29",
    date: "2026-08-29",
    focus: "pernas",
    durationMin: 86,
    intensity: "forte",
    machines: 6,
    muscleGroups: ["coxas", "panturrilhas", "posteriores"],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-08-28",
    date: "2026-08-28",
    focus: "bracos",
    durationMin: 86,
    intensity: "forte",
    machines: 6,
    muscleGroups: ["costas", "braços"],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-08-26",
    date: "2026-08-26",
    focus: "pernas",
    durationMin: 95,
    intensity: "forte",
    machines: 6,
    muscleGroups: ["coxas", "panturrilhas", "posteriores"],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
    cardio: [{ kind: "Bike", minutes: 10 }],
  }),
  w({
    id: "seed-2026-08-24",
    date: "2026-08-24",
    focus: "bracos",
    durationMin: 90,
    intensity: "forte",
    machines: 6,
    muscleGroups: ["peitoral", "costas"],
    core: [
      { exercise: "Abdominal", sets: 3, reps: 12, athlete: "Vânia" },
      { exercise: "Abdominal", sets: 3, reps: 20, athlete: "Geovanil" },
    ],
  }),
  w({
    id: "seed-2026-08-21",
    date: "2026-08-21",
    focus: "pernas",
    durationMin: 80,
    intensity: "forte",
    machines: 6,
    muscleGroups: ["coxas", "panturrilhas", "posteriores"],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-08-18",
    date: "2026-08-18",
    focus: "bracos",
    durationMin: 80,
    intensity: "forte",
    machines: 6,
    muscleGroups: ["peitoral", "braços"],
    extras: "peitoral 4 aparelhos · braços 2 halteres",
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-08-17",
    date: "2026-08-17",
    focus: "bracos",
    durationMin: 85,
    intensity: "forte",
    machines: 6,
    muscleGroups: ["costas", "braços"],
    extras: "costas 4 aparelhos · braços 2 halteres",
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-08-15",
    date: "2026-08-15",
    focus: "bracos",
    durationMin: 45,
    intensity: "forte",
    machines: 6,
    muscleGroups: [],
  }),
  w({
    id: "seed-2026-08-13",
    date: "2026-08-13",
    focus: "pernas",
    durationMin: 80,
    intensity: "forte",
    machines: 7,
    muscleGroups: [],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-08-12",
    date: "2026-08-12",
    focus: "bracos",
    durationMin: 90,
    intensity: "forte",
    machines: 6,
    muscleGroups: [],
    cardio: [{ kind: "Bike", minutes: 10 }],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-08-10",
    date: "2026-08-10",
    focus: "pernas",
    durationMin: 80,
    intensity: "forte",
    machines: 6,
    muscleGroups: [],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-08-07",
    date: "2026-08-07",
    focus: "bracos",
    durationMin: 110,
    intensity: "forte",
    machines: 6,
    muscleGroups: [],
    cardio: [{ kind: "Bike", minutes: 10 }],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-08-04",
    date: "2026-08-04",
    focus: "pernas",
    durationMin: 90,
    intensity: "medio",
    machines: 6,
    muscleGroups: [],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-08-02",
    date: "2026-08-02",
    focus: "bracos",
    durationMin: 90,
    intensity: "medio",
    machines: 5,
    muscleGroups: [],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-07-30",
    date: "2026-07-30",
    focus: "pernas",
    durationMin: 70,
    intensity: "leve",
    machines: 6,
    muscleGroups: [],
    cardio: [{ kind: "Bike", minutes: 15 }],
    notes: "Recuperação ativa",
  }),
  w({
    id: "seed-2026-07-28",
    date: "2026-07-28",
    focus: "bracos",
    durationMin: 150,
    intensity: "medio",
    machines: 6,
    muscleGroups: [],
    cardio: [{ kind: "Bike", minutes: 15 }],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-07-26",
    date: "2026-07-26",
    focus: "pernas",
    durationMin: 150,
    intensity: "medio",
    machines: 6,
    muscleGroups: [],
    cardio: [{ kind: "Bike", minutes: 20 }],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-07-23",
    date: "2026-07-23",
    focus: "bracos",
    durationMin: 100,
    intensity: "forte",
    machines: 6,
    muscleGroups: [],
    cardio: [{ kind: "Bike", minutes: 10 }],
  }),
  w({
    id: "seed-2026-07-22",
    date: "2026-07-22",
    focus: "pernas",
    durationMin: 105,
    intensity: "forte",
    machines: 6,
    muscleGroups: [],
    cardio: [{ kind: "Bike", minutes: 15 }],
    core: [{ exercise: "Abdominal", sets: 3, reps: 12 }],
  }),
  w({
    id: "seed-2026-07-18",
    date: "2026-07-18",
    focus: "bracos",
    durationMin: 110,
    intensity: "forte",
    machines: 6,
    muscleGroups: [],
    cardio: [{ kind: "Bike", minutes: 15 }],
    core: [{ exercise: "Abdominal", sets: 3, reps: 10 }],
  }),
  w({
    id: "seed-2026-07-16",
    date: "2026-07-16",
    focus: "pernas",
    durationMin: 55,
    intensity: "forte",
    machines: 7,
    muscleGroups: ["pernas"],
    cardio: [{ kind: "Bike", minutes: 10 }],
    core: [{ exercise: "Abdominal", sets: 3, reps: 10 }],
  }),
];
